/**
 * @ Author: Ondřej Koumar
 * @ Project: REParser
 * @ Create Date: 2025-10-21
 * @ Description:
 */

#pragma once
#include <string_view>

typedef enum TokenType
{
    LITERAL,
    QUANT_STAR,
    QUANT_PLUS,
    QUANT_QUESTION_MARK,
    QUANT_BRACE_START,
    QUANT_BRACE_END,
    DOT,
    COMMA,
    GROUP_START,
    GROUP_END,
    GROUP_NONCAPTURE_START,
    LOOKAHEAD_POSITIVE_START,
    LOOKAHEAD_NEGATIVE_START,
    LOOKBEHIND_POSITIVE_START,
    LOOKBEHIND_NEGATIVE_START,
    GROUP_NAMED_START,
    ALTERNATION,
    ANCHOR_START,
    ANCHOR_END,
    CHAR_CLASS_START,
    CHAR_CLASS_RANGE,
    CHAR_CLASS_NEGATION,
    CHAR_CLASS_END,
    DIGIT_CLASS,
    NON_DIGIT_CLASS,
    WORD_CHAR_CLASS,
    NON_WORD_CHAR_CLASS,
    WHITESPACE_CLASS,
    NON_WHITESPACE_CLASS,
    ANCHOR_WORD_BOUNDARY,
    ANCHOR_NONWORD_BOUNDARY,
    BACKREFERENCE,
    NAMED_BACKREFERENCE,
    END_OF_INPUT
} TokenType;

struct Token
{
    TokenType type;
    std::string_view text;
};